import { Station, BusSchedule, Seat, MealStop, RouteStop } from '@gsrtc/types';

export const GUJARAT_STATIONS: Station[] = [
  {
    id: 'ADI-GM',
    nameEn: 'Ahmedabad (Geeta Mandir Central)',
    nameGu: 'અમદાવાદ (ગીતા મંદિર સેન્ટ્રલ)',
    code: 'ADI_GM',
    division: 'Ahmedabad',
    isPopular: true,
    latitude: 23.0125,
    longitude: 72.5932,
  },
  {
    id: 'ADI-NN',
    nameEn: 'Ahmedabad (Nehrunagar Cross Rd)',
    nameGu: 'અમદાવાદ (નેહરુનગર ચાર રસ્તા)',
    code: 'ADI_NN',
    division: 'Ahmedabad',
    isPopular: true,
    latitude: 23.0232,
    longitude: 72.5416,
  },
  {
    id: 'ADI-KN',
    nameEn: 'Ahmedabad (Krishnanagar)',
    nameGu: 'અમદાવાદ (કૃષ્ણનગર)',
    code: 'ADI_KN',
    division: 'Ahmedabad',
    isPopular: false,
    latitude: 23.0642,
    longitude: 72.6481,
  },
  {
    id: 'BRD-CT',
    nameEn: 'Vadodara (Central Bus Station)',
    nameGu: 'વડોદરા (સેન્ટ્રલ બસ સ્ટેશન)',
    code: 'BRD_CT',
    division: 'Vadodara',
    isPopular: true,
    latitude: 22.3107,
    longitude: 73.1812,
  },
  {
    id: 'ST-CT',
    nameEn: 'Surat (Central Bus Terminal)',
    nameGu: 'સુરત (સેન્ટ્રલ બસ ટર્મિનલ)',
    code: 'ST_CT',
    division: 'Surat',
    isPopular: true,
    latitude: 21.2052,
    longitude: 72.8398,
  },
  {
    id: 'RJT-CT',
    nameEn: 'Rajkot (Central ST Stand)',
    nameGu: 'રાજકોટ (સેન્ટ્રલ એસ.ટી. સ્ટેન્ડ)',
    code: 'RJT_CT',
    division: 'Rajkot',
    isPopular: true,
    latitude: 22.3039,
    longitude: 70.8022,
  },
  {
    id: 'BVN-CT',
    nameEn: 'Bhavnagar (Ghogha Gate ST Stand)',
    nameGu: 'ભાવનગર (ઘોઘા ગેટ એસ.ટી. સ્ટેન્ડ)',
    code: 'BVN_CT',
    division: 'Bhavnagar',
    isPopular: true,
    latitude: 21.7645,
    longitude: 72.1519,
  },
  {
    id: 'GND-CT',
    nameEn: 'Gandhinagar (Sector 11 ST Stand)',
    nameGu: 'ગાંધીનગર (સેક્ટર ૧૧ એસ.ટી. સ્ટેન્ડ)',
    code: 'GND_CT',
    division: 'Gandhinagar',
    isPopular: true,
    latitude: 23.2156,
    longitude: 72.6369,
  },
  {
    id: 'SOU-NV',
    nameEn: 'Statue of Unity (Ekta Nagar / Kevadia)',
    nameGu: 'સ્ટેચ્યુ ઓફ યુનિટી (એકતા નગર / કેવડિયા)',
    code: 'SOU_NV',
    division: 'Vadodara',
    isPopular: true,
    latitude: 21.838,
    longitude: 73.7191,
  },
  {
    id: 'SMN-VR',
    nameEn: 'Somnath (Veraval Central Stand)',
    nameGu: 'સોમનાથ (વેરાવળ સેન્ટ્રલ સ્ટેન્ડ)',
    code: 'SMN_VR',
    division: 'Junagadh',
    isPopular: true,
    latitude: 20.9004,
    longitude: 70.3667,
  },
  {
    id: 'DWK-CT',
    nameEn: 'Dwarka (Dwarkadhish Dham ST Stand)',
    nameGu: 'દ્વારકા (દ્વારકાધીશ ધામ એસ.ટી. સ્ટેન્ડ)',
    code: 'DWK_CT',
    division: 'Jamnagar',
    isPopular: true,
    latitude: 22.2442,
    longitude: 68.9685,
  },
  {
    id: 'BHJ-KT',
    nameEn: 'Bhuj (Kutch White Desert Gateway)',
    nameGu: 'ભુજ (કચ્છ વ્હાઇટ ડેઝર્ટ ગેટવે)',
    code: 'BHJ_KT',
    division: 'Bhuj',
    isPopular: true,
    latitude: 23.242,
    longitude: 69.6669,
  },
  {
    id: 'JND-CT',
    nameEn: 'Junagadh (Majewadi Gate ST Stand)',
    nameGu: 'જૂનાગઢ (મજેવડી ગેટ એસ.ટી. સ્ટેન્ડ)',
    code: 'JND_CT',
    division: 'Junagadh',
    isPopular: false,
    latitude: 21.5222,
    longitude: 70.4579,
  },
  {
    id: 'JMN-CT',
    nameEn: 'Jamnagar (Lal Bungalow Stand)',
    nameGu: 'જામનગર (લાલ બંગલા સ્ટેન્ડ)',
    code: 'JMN_CT',
    division: 'Jamnagar',
    isPopular: false,
    latitude: 22.4707,
    longitude: 70.0577,
  },
  {
    id: 'AMB-CT',
    nameEn: 'Ambaji (Gabbar Tirth ST Stand)',
    nameGu: 'અંબાજી (ગબ્બર તીર્થ એસ.ટી. સ્ટેન્ડ)',
    code: 'AMB_CT',
    division: 'Palanpur',
    isPopular: true,
    latitude: 24.3312,
    longitude: 72.8521,
  },
  {
    id: 'AND-CT',
    nameEn: 'Anand (Milk City Bus Stand)',
    nameGu: 'આણંદ (મિલ્ક સિટી બસ સ્ટેન્ડ)',
    code: 'AND_CT',
    division: 'Vadodara',
    isPopular: false,
    latitude: 22.5645,
    longitude: 72.9289,
  },
  {
    id: 'BHR-CT',
    nameEn: 'Bharuch (Zadeshwar Cross Stand)',
    nameGu: 'ભરૂચ (ઝાડેશ્વર ચોકડી સ્ટેન્ડ)',
    code: 'BHR_CT',
    division: 'Bharuch',
    isPopular: false,
    latitude: 21.7051,
    longitude: 72.9959,
  },
  {
    id: 'VAP-CT',
    nameEn: 'Vapi (GIDC Bus Terminal)',
    nameGu: 'વાપી (જી.આઈ.ડી.સી. બસ ટર્મિનલ)',
    code: 'VAP_CT',
    division: 'Valsad',
    isPopular: false,
    latitude: 20.3725,
    longitude: 72.9106,
  }
];

// Helper to generate realistic seats for a bus
export function generateBusSeats(busClass: string, totalSeats: number, basePrice: number): Seat[] {
  const seats: Seat[] = [];
  const isSleeper = busClass.includes('SLEEPER');

  if (isSleeper) {
    // 15 Lower Deck berths + 15 Upper Deck berths = 30 berths
    const lowerBerths = Math.min(15, Math.floor(totalSeats / 2));
    const upperBerths = totalSeats - lowerBerths;

    // Lower Deck (Row 1-5, Col 1-3: single on left, double on right)
    for (let i = 1; i <= lowerBerths; i++) {
      const row = Math.ceil(i / 3);
      const col = ((i - 1) % 3) + 1;
      const isLadies = i === 1 || i === 2; // Priority ladies berths
      const isDivyang = i === 3;
      seats.push({
        seatNumber: i,
        seatLabel: `L${i}`,
        deck: 'LOWER',
        row,
        col,
        seatType: 'SLEEPER_LOWER',
        quota: isLadies ? 'LADIES' : isDivyang ? 'DIVYANG' : 'GENERAL',
        isWindow: col === 1 || col === 3,
        basePrice,
      });
    }

    // Upper Deck
    for (let i = 1; i <= upperBerths; i++) {
      const seatNum = lowerBerths + i;
      const row = Math.ceil(i / 3);
      const col = ((i - 1) % 3) + 1;
      seats.push({
        seatNumber: seatNum,
        seatLabel: `U${i}`,
        deck: 'UPPER',
        row,
        col,
        seatType: 'SLEEPER_UPPER',
        quota: 'GENERAL',
        isWindow: col === 1 || col === 3,
        basePrice: Math.round(basePrice * 0.95), // upper slightly cheaper
      });
    }
  } else {
    // Seater: 2x2 or 3x2 layout
    const isExpress2x2 = busClass === 'GURJARNAGARI' || busClass === 'VOLVO_AC' || busClass === 'ELECTRIC_EXPRESS';
    const colsPerRow = isExpress2x2 ? 4 : 5;
    const totalRows = Math.ceil(totalSeats / colsPerRow);

    for (let i = 1; i <= totalSeats; i++) {
      const row = Math.ceil(i / colsPerRow);
      const col = ((i - 1) % colsPerRow) + 1;
      const isLadies = i >= 3 && i <= 8; // Seats 3 to 8 designated for Women
      const isDivyang = i === 1 || i === 2; // Seats 1 & 2 for Divyang

      seats.push({
        seatNumber: i,
        seatLabel: `${i}`,
        deck: 'LOWER',
        row,
        col,
        seatType: 'SEATER',
        quota: isLadies ? 'LADIES' : isDivyang ? 'DIVYANG' : 'GENERAL',
        isWindow: col === 1 || col === colsPerRow,
        basePrice,
      });
    }
  }

  return seats;
}

export const INITIAL_SCHEDULES: BusSchedule[] = [
  // 1. Ahmedabad -> Statue of Unity (High demand)
  {
    id: 'SCH-ADI-SOU-01',
    busNumber: 'GJ-18-Z-9812',
    busClass: 'VOLVO_AC',
    busNameEn: 'Volvo Multi-Axle AC Seater (Ekta Express)',
    busNameGu: 'વોલ્વો મલ્ટી-એક્સલ એ.સી. (એકતા એક્સપ્રેસ)',
    sourceStationId: 'ADI-GM',
    destinationStationId: 'SOU-NV',
    departureTime: '06:00 AM',
    arrivalTime: '09:45 AM',
    durationFormatted: '3h 45m',
    distanceKm: 198,
    baseFare: 420,
    amenities: {
      hasAc: true,
      hasCharging: true,
      hasGps: true,
      hasWater: true,
      hasWifi: true,
      hasBlanket: true,
    },
    mealStop: {
      id: 'MEAL-01',
      locationName: 'Vadodara Bypass Food Plaza (Honest)',
      highwayName: 'NH-48 Golden Quadrilateral',
      durationMinutes: 25,
      expectedArrivalTime: '07:45 AM',
      type: 'TEA_BREAK',
    },
    routeStops: [
      {
        stationId: 'ADI-GM',
        stationNameEn: 'Ahmedabad (Geeta Mandir Central)',
        stationNameGu: 'અમદાવાદ (ગીતા મંદિર સેન્ટ્રલ)',
        scheduledTime: '05:45 AM',
        departureTime: '06:00 AM',
        isBoardingPoint: true,
        isDroppingPoint: false,
        platform: 'PF-4 (Express)',
        distanceFromOriginKm: 0,
      },
      {
        stationId: 'BRD-CT',
        stationNameEn: 'Vadodara Central Bus Station',
        stationNameGu: 'વડોદરા સેન્ટ્રલ બસ સ્ટેશન',
        scheduledTime: '07:55 AM',
        departureTime: '08:10 AM',
        isBoardingPoint: true,
        isDroppingPoint: true,
        platform: 'PF-1',
        distanceFromOriginKm: 112,
      },
      {
        stationId: 'SOU-NV',
        stationNameEn: 'Statue of Unity (Ekta Nagar)',
        stationNameGu: 'સ્ટેચ્યુ ઓફ યુનિટી (એકતા નગર)',
        scheduledTime: '09:45 AM',
        departureTime: '09:45 AM',
        isBoardingPoint: false,
        isDroppingPoint: true,
        platform: 'Main Gate Terminal',
        distanceFromOriginKm: 198,
      },
    ],
    totalSeats: 40,
    seats: generateBusSeats('VOLVO_AC', 40, 420),
    isElectric: false,
    isDirectExpress: true,
    rating: 4.8,
  },

  // 2. Ahmedabad -> Statue of Unity (Electric Green Bus)
  {
    id: 'SCH-ADI-SOU-02',
    busNumber: 'GJ-01-EV-4021',
    busClass: 'ELECTRIC_EXPRESS',
    busNameEn: 'Green Gujarat Electric AC Superfast',
    busNameGu: 'ગ્રીન ગુજરાત ઇલેક્ટ્રિક એ.સી. સુપરફાસ્ટ',
    sourceStationId: 'ADI-GM',
    destinationStationId: 'SOU-NV',
    departureTime: '08:30 AM',
    arrivalTime: '12:30 PM',
    durationFormatted: '4h 00m',
    distanceKm: 198,
    baseFare: 360,
    amenities: {
      hasAc: true,
      hasCharging: true,
      hasGps: true,
      hasWater: true,
      hasWifi: false,
    },
    mealStop: {
      id: 'MEAL-02',
      locationName: 'Anand Green Highway Plaza',
      highwayName: 'NE-1 Express Highway',
      durationMinutes: 20,
      expectedArrivalTime: '09:50 AM',
      type: 'TEA_BREAK',
    },
    routeStops: [
      {
        stationId: 'ADI-GM',
        stationNameEn: 'Ahmedabad (Geeta Mandir Central)',
        stationNameGu: 'અમદાવાદ (ગીતા મંદિર સેન્ટ્રલ)',
        scheduledTime: '08:15 AM',
        departureTime: '08:30 AM',
        isBoardingPoint: true,
        isDroppingPoint: false,
        platform: 'PF-EV 1',
        distanceFromOriginKm: 0,
      },
      {
        stationId: 'AND-CT',
        stationNameEn: 'Anand (Milk City Bus Stand)',
        stationNameGu: 'આણંદ (મિલ્ક સિટી બસ સ્ટેન્ડ)',
        scheduledTime: '09:40 AM',
        departureTime: '09:50 AM',
        isBoardingPoint: true,
        isDroppingPoint: true,
        platform: 'PF-2',
        distanceFromOriginKm: 75,
      },
      {
        stationId: 'SOU-NV',
        stationNameEn: 'Statue of Unity (Ekta Nagar)',
        stationNameGu: 'સ્ટેચ્યુ ઓફ યુનિટી (એકતા નગર)',
        scheduledTime: '12:30 PM',
        departureTime: '12:30 PM',
        isBoardingPoint: false,
        isDroppingPoint: true,
        platform: 'Shreshtha Bharat Bhawan',
        distanceFromOriginKm: 198,
      },
    ],
    totalSeats: 42,
    seats: generateBusSeats('ELECTRIC_EXPRESS', 42, 360),
    isElectric: true,
    isDirectExpress: false,
    rating: 4.7,
  },

  // 3. Ahmedabad -> Surat (Gurjarnagari Express)
  {
    id: 'SCH-ADI-ST-01',
    busNumber: 'GJ-18-Z-4532',
    busClass: 'GURJARNAGARI',
    busNameEn: 'Gurjarnagari 2x2 Express (Diamond Line)',
    busNameGu: 'ગુર્જરનગરી ૨x૨ એક્સપ્રેસ (ડાયમંડ લાઇન)',
    sourceStationId: 'ADI-GM',
    destinationStationId: 'ST-CT',
    departureTime: '07:15 AM',
    arrivalTime: '11:45 AM',
    durationFormatted: '4h 30m',
    distanceKm: 265,
    baseFare: 260,
    amenities: {
      hasAc: false,
      hasCharging: true,
      hasGps: true,
      hasWater: false,
      hasWifi: false,
    },
    mealStop: {
      id: 'MEAL-03',
      locationName: 'Bharuch Zadeshwar Food Court',
      highwayName: 'NH-48 Highway Plaza',
      durationMinutes: 30,
      expectedArrivalTime: '09:45 AM',
      type: 'TEA_BREAK',
    },
    routeStops: [
      {
        stationId: 'ADI-GM',
        stationNameEn: 'Ahmedabad (Geeta Mandir Central)',
        stationNameGu: 'અમદાવાદ (ગીતા મંદિર સેન્ટ્રલ)',
        scheduledTime: '07:00 AM',
        departureTime: '07:15 AM',
        isBoardingPoint: true,
        isDroppingPoint: false,
        platform: 'PF-7',
        distanceFromOriginKm: 0,
      },
      {
        stationId: 'BRD-CT',
        stationNameEn: 'Vadodara Central Bus Station',
        stationNameGu: 'વડોદરા સેન્ટ્રલ બસ સ્ટેશન',
        scheduledTime: '09:00 AM',
        departureTime: '09:15 AM',
        isBoardingPoint: true,
        isDroppingPoint: true,
        platform: 'PF-3',
        distanceFromOriginKm: 112,
      },
      {
        stationId: 'BHR-CT',
        stationNameEn: 'Bharuch Zadeshwar Stand',
        stationNameGu: 'ભરૂચ ઝાડેશ્વર સ્ટેન્ડ',
        scheduledTime: '10:20 AM',
        departureTime: '10:30 AM',
        isBoardingPoint: true,
        isDroppingPoint: true,
        platform: 'PF-2',
        distanceFromOriginKm: 192,
      },
      {
        stationId: 'ST-CT',
        stationNameEn: 'Surat (Central Bus Terminal)',
        stationNameGu: 'સુરત (સેન્ટ્રલ બસ ટર્મિનલ)',
        scheduledTime: '11:45 AM',
        departureTime: '11:45 AM',
        isBoardingPoint: false,
        isDroppingPoint: true,
        platform: 'PF-12',
        distanceFromOriginKm: 265,
      },
    ],
    totalSeats: 48,
    seats: generateBusSeats('GURJARNAGARI', 48, 260),
    isElectric: false,
    isDirectExpress: false,
    rating: 4.5,
  },

  // 4. Ahmedabad -> Somnath (Night Sleeper 2+1)
  {
    id: 'SCH-ADI-SMN-01',
    busNumber: 'GJ-18-Z-7788',
    busClass: 'SLEEPER_NON_AC',
    busNameEn: 'Non-AC 2+1 Sleeper (Somnath Darshan Night Service)',
    busNameGu: 'નોન-એ.સી. ૨+૧ સ્લીપર (સોમનાથ દર્શન નાઇટ સર્વિસ)',
    sourceStationId: 'ADI-GM',
    destinationStationId: 'SMN-VR',
    departureTime: '09:30 PM',
    arrivalTime: '06:15 AM',
    durationFormatted: '8h 45m',
    distanceKm: 410,
    baseFare: 495,
    amenities: {
      hasAc: false,
      hasCharging: true,
      hasGps: true,
      hasWater: true,
      hasWifi: false,
    },
    mealStop: {
      id: 'MEAL-04',
      locationName: 'Chotila Chamunda Krupa Highway Bhojanalay',
      highwayName: 'Ahmedabad-Rajkot Highway',
      durationMinutes: 35,
      expectedArrivalTime: '12:15 AM',
      type: 'DINNER',
    },
    routeStops: [
      {
        stationId: 'ADI-GM',
        stationNameEn: 'Ahmedabad (Geeta Mandir Central)',
        stationNameGu: 'અમદાવાદ (ગીતા મંદિર સેન્ટ્રલ)',
        scheduledTime: '09:15 PM',
        departureTime: '09:30 PM',
        isBoardingPoint: true,
        isDroppingPoint: false,
        platform: 'PF-14 (Sleeper Bay)',
        distanceFromOriginKm: 0,
      },
      {
        stationId: 'ADI-NN',
        stationNameEn: 'Ahmedabad (Nehrunagar)',
        stationNameGu: 'અમદાવાદ (નેહરુનગર)',
        scheduledTime: '09:55 PM',
        departureTime: '10:05 PM',
        isBoardingPoint: true,
        isDroppingPoint: false,
        platform: 'Roadside ST Pickup',
        distanceFromOriginKm: 8,
      },
      {
        stationId: 'RJT-CT',
        stationNameEn: 'Rajkot (Central ST Stand)',
        stationNameGu: 'રાજકોટ (સેન્ટ્રલ એસ.ટી. સ્ટેન્ડ)',
        scheduledTime: '01:30 AM',
        departureTime: '01:45 AM',
        isBoardingPoint: true,
        isDroppingPoint: true,
        platform: 'PF-2',
        distanceFromOriginKm: 215,
      },
      {
        stationId: 'JND-CT',
        stationNameEn: 'Junagadh (Majewadi Gate)',
        stationNameGu: 'જૂનાગઢ (મજેવડી ગેટ)',
        scheduledTime: '03:45 AM',
        departureTime: '04:00 AM',
        isBoardingPoint: true,
        isDroppingPoint: true,
        platform: 'PF-1',
        distanceFromOriginKm: 315,
      },
      {
        stationId: 'SMN-VR',
        stationNameEn: 'Somnath (Veraval Central Stand)',
        stationNameGu: 'સોમનાથ (વેરાવળ સેન્ટ્રલ સ્ટેન્ડ)',
        scheduledTime: '06:15 AM',
        departureTime: '06:15 AM',
        isBoardingPoint: false,
        isDroppingPoint: true,
        platform: 'Temple Gate Terminal',
        distanceFromOriginKm: 410,
      },
    ],
    totalSeats: 30,
    seats: generateBusSeats('SLEEPER_NON_AC', 30, 495),
    isElectric: false,
    isDirectExpress: false,
    rating: 4.6,
  },

  // 5. Ahmedabad -> Rajkot (Direct Express)
  {
    id: 'SCH-ADI-RJT-01',
    busNumber: 'GJ-18-Z-3321',
    busClass: 'EXPRESS',
    busNameEn: 'Saurashtra Express Non-Stop',
    busNameGu: 'સૌરાષ્ટ્ર એક્સપ્રેસ નોન-સ્ટોપ',
    sourceStationId: 'ADI-GM',
    destinationStationId: 'RJT-CT',
    departureTime: '05:30 AM',
    arrivalTime: '09:45 AM',
    durationFormatted: '4h 15m',
    distanceKm: 215,
    baseFare: 195,
    amenities: {
      hasAc: false,
      hasCharging: true,
      hasGps: true,
      hasWater: false,
      hasWifi: false,
    },
    mealStop: {
      id: 'MEAL-05',
      locationName: 'Limbdi Highway Honest Plaza',
      highwayName: 'NH-47 Rajkot Highway',
      durationMinutes: 20,
      expectedArrivalTime: '07:15 AM',
      type: 'TEA_BREAK',
    },
    routeStops: [
      {
        stationId: 'ADI-GM',
        stationNameEn: 'Ahmedabad (Geeta Mandir Central)',
        stationNameGu: 'અમદાવાદ (ગીતા મંદિર સેન્ટ્રલ)',
        scheduledTime: '05:15 AM',
        departureTime: '05:30 AM',
        isBoardingPoint: true,
        isDroppingPoint: false,
        platform: 'PF-6',
        distanceFromOriginKm: 0,
      },
      {
        stationId: 'RJT-CT',
        stationNameEn: 'Rajkot (Central ST Stand)',
        stationNameGu: 'રાજકોટ (સેન્ટ્રલ એસ.ટી. સ્ટેન્ડ)',
        scheduledTime: '09:45 AM',
        departureTime: '09:45 AM',
        isBoardingPoint: false,
        isDroppingPoint: true,
        platform: 'PF-4',
        distanceFromOriginKm: 215,
      },
    ],
    totalSeats: 52,
    seats: generateBusSeats('EXPRESS', 52, 195),
    isElectric: false,
    isDirectExpress: true,
    rating: 4.4,
  },

  // 6. Ahmedabad -> Bhuj (Kutch Sleeper Volvo AC)
  {
    id: 'SCH-ADI-BHJ-01',
    busNumber: 'GJ-18-Z-1008',
    busClass: 'VOLVO_AC',
    busNameEn: 'Ashwamegh Volvo AC Sleeper (Kutch White Desert Express)',
    busNameGu: 'અશ્વમેઘ વોલ્વો એ.સી. સ્લીપર (કચ્છ વ્હાઇટ ડેઝર્ટ એક્સપ્રેસ)',
    sourceStationId: 'ADI-GM',
    destinationStationId: 'BHJ-KT',
    departureTime: '10:00 PM',
    arrivalTime: '06:30 AM',
    durationFormatted: '8h 30m',
    distanceKm: 385,
    baseFare: 720,
    amenities: {
      hasAc: true,
      hasCharging: true,
      hasGps: true,
      hasWater: true,
      hasWifi: true,
      hasBlanket: true,
    },
    mealStop: {
      id: 'MEAL-06',
      locationName: 'Samakhiali Highway Food Paradise',
      highwayName: 'NH-8A Kutch Gateway',
      durationMinutes: 30,
      expectedArrivalTime: '01:30 AM',
      type: 'DINNER',
    },
    routeStops: [
      {
        stationId: 'ADI-GM',
        stationNameEn: 'Ahmedabad (Geeta Mandir Central)',
        stationNameGu: 'અમદાવાદ (ગીતા મંદિર સેન્ટ્રલ)',
        scheduledTime: '09:45 PM',
        departureTime: '10:00 PM',
        isBoardingPoint: true,
        isDroppingPoint: false,
        platform: 'PF-16',
        distanceFromOriginKm: 0,
      },
      {
        stationId: 'BHJ-KT',
        stationNameEn: 'Bhuj (Kutch ST Stand)',
        stationNameGu: 'ભુજ (કચ્છ એસ.ટી. સ્ટેન્ડ)',
        scheduledTime: '06:30 AM',
        departureTime: '06:30 AM',
        isBoardingPoint: false,
        isDroppingPoint: true,
        platform: 'PF-1',
        distanceFromOriginKm: 385,
      },
    ],
    totalSeats: 30,
    seats: generateBusSeats('VOLVO_AC', 30, 720),
    isElectric: false,
    isDirectExpress: true,
    rating: 4.9,
  },

  // 7. Vadodara -> Statue of Unity
  {
    id: 'SCH-BRD-SOU-01',
    busNumber: 'GJ-06-EV-8841',
    busClass: 'ELECTRIC_EXPRESS',
    busNameEn: 'Sardar Vallabhbhai Patel Heritage EV Express',
    busNameGu: 'સરદાર વલ્લભભાઈ પટેલ હેરિટેજ ઇ.વી. એક્સપ્રેસ',
    sourceStationId: 'BRD-CT',
    destinationStationId: 'SOU-NV',
    departureTime: '08:00 AM',
    arrivalTime: '09:45 AM',
    durationFormatted: '1h 45m',
    distanceKm: 88,
    baseFare: 160,
    amenities: {
      hasAc: true,
      hasCharging: true,
      hasGps: true,
      hasWater: true,
      hasWifi: false,
    },
    routeStops: [
      {
        stationId: 'BRD-CT',
        stationNameEn: 'Vadodara Central Bus Station',
        stationNameGu: 'વડોદરા સેન્ટ્રલ બસ સ્ટેશન',
        scheduledTime: '07:45 AM',
        departureTime: '08:00 AM',
        isBoardingPoint: true,
        isDroppingPoint: false,
        platform: 'PF-5',
        distanceFromOriginKm: 0,
      },
      {
        stationId: 'SOU-NV',
        stationNameEn: 'Statue of Unity (Ekta Nagar)',
        stationNameGu: 'સ્ટેચ્યુ ઓફ યુનિટી (એકતા નગર)',
        scheduledTime: '09:45 AM',
        departureTime: '09:45 AM',
        isBoardingPoint: false,
        isDroppingPoint: true,
        platform: 'Ekta Nagar Main Stand',
        distanceFromOriginKm: 88,
      },
    ],
    totalSeats: 40,
    seats: generateBusSeats('ELECTRIC_EXPRESS', 40, 160),
    isElectric: true,
    isDirectExpress: true,
    rating: 4.8,
  },

  // 8. Bhavnagar -> Ahmedabad
  {
    id: 'SCH-BVN-ADI-01',
    busNumber: 'GJ-04-Z-2290',
    busClass: 'GURJARNAGARI',
    busNameEn: 'Gohilwad Gurjarnagari Express',
    busNameGu: 'ગોહિલવાડ ગુર્જરનગરી એક્સપ્રેસ',
    sourceStationId: 'BVN-CT',
    destinationStationId: 'ADI-GM',
    departureTime: '06:15 AM',
    arrivalTime: '10:30 AM',
    durationFormatted: '4h 15m',
    distanceKm: 205,
    baseFare: 210,
    amenities: {
      hasAc: false,
      hasCharging: true,
      hasGps: true,
      hasWater: false,
      hasWifi: false,
    },
    mealStop: {
      id: 'MEAL-07',
      locationName: 'Dhandhuka Swaminarayan Food Court',
      highwayName: 'Bhavnagar-Ahmedabad State Highway',
      durationMinutes: 20,
      expectedArrivalTime: '08:15 AM',
      type: 'TEA_BREAK',
    },
    routeStops: [
      {
        stationId: 'BVN-CT',
        stationNameEn: 'Bhavnagar (Ghogha Gate Stand)',
        stationNameGu: 'ભાવનગર (ઘોઘા ગેટ સ્ટેન્ડ)',
        scheduledTime: '06:00 AM',
        departureTime: '06:15 AM',
        isBoardingPoint: true,
        isDroppingPoint: false,
        platform: 'PF-2',
        distanceFromOriginKm: 0,
      },
      {
        stationId: 'ADI-GM',
        stationNameEn: 'Ahmedabad (Geeta Mandir Central)',
        stationNameGu: 'અમદાવાદ (ગીતા મંદિર સેન્ટ્રલ)',
        scheduledTime: '10:30 AM',
        departureTime: '10:30 AM',
        isBoardingPoint: false,
        isDroppingPoint: true,
        platform: 'PF-9',
        distanceFromOriginKm: 205,
      },
    ],
    totalSeats: 48,
    seats: generateBusSeats('GURJARNAGARI', 48, 210),
    isElectric: false,
    isDirectExpress: false,
    rating: 4.6,
  }
];
